# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/jkchoi/Documents/git/p4-netfpga-live/contrib-projects/sume-sdnet-switch/projects/switch_calc_pifo/simple_sume_switch/hw/project/simple_sume_switch.srcs/sources_1/ip/buffer_meta_128_4096/buffer_meta_128_4096.xci
# IP: The module: 'buffer_meta_128_4096' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/jkchoi/Documents/git/p4-netfpga-live/contrib-projects/sume-sdnet-switch/projects/switch_calc_pifo/simple_sume_switch/hw/project/simple_sume_switch.srcs/sources_1/ip/buffer_meta_128_4096/buffer_meta_128_4096_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'buffer_meta_128_4096'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/jkchoi/Documents/git/p4-netfpga-live/contrib-projects/sume-sdnet-switch/projects/switch_calc_pifo/simple_sume_switch/hw/project/simple_sume_switch.srcs/sources_1/ip/buffer_meta_128_4096/buffer_meta_128_4096.xci
# IP: The module: 'buffer_meta_128_4096' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/jkchoi/Documents/git/p4-netfpga-live/contrib-projects/sume-sdnet-switch/projects/switch_calc_pifo/simple_sume_switch/hw/project/simple_sume_switch.srcs/sources_1/ip/buffer_meta_128_4096/buffer_meta_128_4096_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'buffer_meta_128_4096'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
