clean:
	make -C bram_wrapper clean
	make -C bypass_checker clean
	make -C extern_calc clean
	make -C output_queue clean
	make -C pifo_calendar clean

run_all:
	# make -C bram_wrapper run_all
	make -C bypass_checker run_all
	make -C extern_calc run_all
	make -C output_queue run_all
	make -C pifo_calendar run_all
