# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/jkchoi/Documents/git/p4-netfpga-live/lib/hw/std/constraints/generic_bit.xdc

# XDC: /home/jkchoi/Documents/git/p4-netfpga-live/contrib-projects/sume-sdnet-switch/projects/switch_calc_pifo/simple_sume_switch/hw/constraints/nf_sume_general.xdc

# XDC: /home/jkchoi/Documents/git/p4-netfpga-live/contrib-projects/sume-sdnet-switch/projects/switch_calc_pifo/simple_sume_switch/hw/constraints/nf_sume_10g.xdc

# IP: ip/input_arbiter_ip/input_arbiter_ip.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==input_arbiter_ip || ORIG_REF_NAME==input_arbiter_ip} -quiet] -quiet

# Block Designs: bd/control_sub/control_sub.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==control_sub || ORIG_REF_NAME==control_sub} -quiet] -quiet

# IP: bd/control_sub/ip/control_sub_axi_iic_0_0/control_sub_axi_iic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==control_sub_axi_iic_0_0 || ORIG_REF_NAME==control_sub_axi_iic_0_0} -quiet] -quiet

# IP: bd/control_sub/ip/control_sub_axi_uartlite_0_0/control_sub_axi_uartlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==control_sub_axi_uartlite_0_0 || ORIG_REF_NAME==control_sub_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/control_sub/ip/control_sub_clk_wiz_1_0/control_sub_clk_wiz_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==control_sub_clk_wiz_1_0 || ORIG_REF_NAME==control_sub_clk_wiz_1_0} -quiet] -quiet

# IP: bd/control_sub/ip/control_sub_mdm_1_0/control_sub_mdm_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==control_sub_mdm_1_0 || ORIG_REF_NAME==control_sub_mdm_1_0} -quiet] -quiet

# IP: bd/control_sub/ip/control_sub_microblaze_0_0/control_sub_microblaze_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==control_sub_microblaze_0_0 || ORIG_REF_NAME==control_sub_microblaze_0_0} -quiet] -quiet

# IP: bd/control_sub/ip/control_sub_microblaze_0_axi_intc_0/control_sub_microblaze_0_axi_intc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==control_sub_microblaze_0_axi_intc_0 || ORIG_REF_NAME==control_sub_microblaze_0_axi_intc_0} -quiet] -quiet

# IP: bd/control_sub/ip/control_sub_microblaze_0_axi_periph_0/control_sub_microblaze_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==control_sub_microblaze_0_axi_periph_0 || ORIG_REF_NAME==control_sub_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/control_sub/ip/control_sub_microblaze_0_xlconcat_0/control_sub_microblaze_0_xlconcat_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==control_sub_microblaze_0_xlconcat_0 || ORIG_REF_NAME==control_sub_microblaze_0_xlconcat_0} -quiet] -quiet

# IP: bd/control_sub/ip/control_sub_rst_clk_wiz_1_100M_0/control_sub_rst_clk_wiz_1_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==control_sub_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==control_sub_rst_clk_wiz_1_100M_0} -quiet] -quiet

# IP: bd/control_sub/ip/control_sub_dlmb_bram_if_cntlr_0/control_sub_dlmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==control_sub_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==control_sub_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/control_sub/ip/control_sub_dlmb_v10_0/control_sub_dlmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==control_sub_dlmb_v10_0 || ORIG_REF_NAME==control_sub_dlmb_v10_0} -quiet] -quiet

# IP: bd/control_sub/ip/control_sub_ilmb_bram_if_cntlr_0/control_sub_ilmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==control_sub_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==control_sub_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/control_sub/ip/control_sub_ilmb_v10_0/control_sub_ilmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==control_sub_ilmb_v10_0 || ORIG_REF_NAME==control_sub_ilmb_v10_0} -quiet] -quiet

# IP: bd/control_sub/ip/control_sub_lmb_bram_0/control_sub_lmb_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==control_sub_lmb_bram_0 || ORIG_REF_NAME==control_sub_lmb_bram_0} -quiet] -quiet

# IP: bd/control_sub/ip/control_sub_xbar_1/control_sub_xbar_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==control_sub_xbar_1 || ORIG_REF_NAME==control_sub_xbar_1} -quiet] -quiet

# IP: bd/control_sub/ip/control_sub_axi_interconnect_0_0/control_sub_axi_interconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==control_sub_axi_interconnect_0_0 || ORIG_REF_NAME==control_sub_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/control_sub/ip/control_sub_pcie_reset_inv_0/control_sub_pcie_reset_inv_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==control_sub_pcie_reset_inv_0 || ORIG_REF_NAME==control_sub_pcie_reset_inv_0} -quiet] -quiet

# IP: bd/control_sub/ip/control_sub_axis_dwidth_dma_tx_0/control_sub_axis_dwidth_dma_tx_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==control_sub_axis_dwidth_dma_tx_0 || ORIG_REF_NAME==control_sub_axis_dwidth_dma_tx_0} -quiet] -quiet

# IP: bd/control_sub/ip/control_sub_axis_dwidth_dma_rx_0/control_sub_axis_dwidth_dma_rx_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==control_sub_axis_dwidth_dma_rx_0 || ORIG_REF_NAME==control_sub_axis_dwidth_dma_rx_0} -quiet] -quiet

# IP: bd/control_sub/ip/control_sub_axis_fifo_10g_rx_0/control_sub_axis_fifo_10g_rx_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==control_sub_axis_fifo_10g_rx_0 || ORIG_REF_NAME==control_sub_axis_fifo_10g_rx_0} -quiet] -quiet

# IP: bd/control_sub/ip/control_sub_axis_fifo_10g_tx_0/control_sub_axis_fifo_10g_tx_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==control_sub_axis_fifo_10g_tx_0 || ORIG_REF_NAME==control_sub_axis_fifo_10g_tx_0} -quiet] -quiet

# IP: bd/control_sub/ip/control_sub_nf_riffa_dma_1_0/control_sub_nf_riffa_dma_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==control_sub_nf_riffa_dma_1_0 || ORIG_REF_NAME==control_sub_nf_riffa_dma_1_0} -quiet] -quiet

# IP: bd/control_sub/ip/control_sub_axi_clock_converter_0_0/control_sub_axi_clock_converter_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==control_sub_axi_clock_converter_0_0 || ORIG_REF_NAME==control_sub_axi_clock_converter_0_0} -quiet] -quiet

# IP: bd/control_sub/ip/control_sub_pcie3_7x_1_0/control_sub_pcie3_7x_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==control_sub_pcie3_7x_1_0 || ORIG_REF_NAME==control_sub_pcie3_7x_1_0} -quiet] -quiet

# IP: bd/control_sub/ip/control_sub_xbar_0/control_sub_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==control_sub_xbar_0 || ORIG_REF_NAME==control_sub_xbar_0} -quiet] -quiet

# IP: bd/control_sub/ip/control_sub_m08_data_fifo_0/control_sub_m08_data_fifo_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==control_sub_m08_data_fifo_0 || ORIG_REF_NAME==control_sub_m08_data_fifo_0} -quiet] -quiet

# IP: bd/control_sub/ip/control_sub_m07_data_fifo_0/control_sub_m07_data_fifo_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==control_sub_m07_data_fifo_0 || ORIG_REF_NAME==control_sub_m07_data_fifo_0} -quiet] -quiet

# IP: bd/control_sub/ip/control_sub_m06_data_fifo_0/control_sub_m06_data_fifo_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==control_sub_m06_data_fifo_0 || ORIG_REF_NAME==control_sub_m06_data_fifo_0} -quiet] -quiet

# IP: bd/control_sub/ip/control_sub_m05_data_fifo_0/control_sub_m05_data_fifo_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==control_sub_m05_data_fifo_0 || ORIG_REF_NAME==control_sub_m05_data_fifo_0} -quiet] -quiet

# IP: bd/control_sub/ip/control_sub_m04_data_fifo_0/control_sub_m04_data_fifo_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==control_sub_m04_data_fifo_0 || ORIG_REF_NAME==control_sub_m04_data_fifo_0} -quiet] -quiet

# IP: bd/control_sub/ip/control_sub_m03_data_fifo_0/control_sub_m03_data_fifo_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==control_sub_m03_data_fifo_0 || ORIG_REF_NAME==control_sub_m03_data_fifo_0} -quiet] -quiet

# IP: bd/control_sub/ip/control_sub_m02_data_fifo_0/control_sub_m02_data_fifo_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==control_sub_m02_data_fifo_0 || ORIG_REF_NAME==control_sub_m02_data_fifo_0} -quiet] -quiet

# IP: bd/control_sub/ip/control_sub_m01_data_fifo_0/control_sub_m01_data_fifo_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==control_sub_m01_data_fifo_0 || ORIG_REF_NAME==control_sub_m01_data_fifo_0} -quiet] -quiet

# IP: bd/control_sub/ip/control_sub_m00_data_fifo_0/control_sub_m00_data_fifo_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==control_sub_m00_data_fifo_0 || ORIG_REF_NAME==control_sub_m00_data_fifo_0} -quiet] -quiet

# IP: bd/control_sub/ip/control_sub_s00_data_fifo_0/control_sub_s00_data_fifo_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==control_sub_s00_data_fifo_0 || ORIG_REF_NAME==control_sub_s00_data_fifo_0} -quiet] -quiet

# IP: bd/control_sub/ip/control_sub_auto_cc_0/control_sub_auto_cc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==control_sub_auto_cc_0 || ORIG_REF_NAME==control_sub_auto_cc_0} -quiet] -quiet

# IP: ip/nf_sume_sdnet_ip/nf_sume_sdnet_ip.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==nf_sume_sdnet_ip || ORIG_REF_NAME==nf_sume_sdnet_ip} -quiet] -quiet

# IP: ip/axi_10g_ethernet_nonshared/axi_10g_ethernet_nonshared.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi_10g_ethernet_nonshared || ORIG_REF_NAME==axi_10g_ethernet_nonshared} -quiet] -quiet

# Block Designs: ip/axi_10g_ethernet_nonshared/bd_0/bd_7ad4.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_7ad4 || ORIG_REF_NAME==bd_7ad4} -quiet] -quiet

# IP: ip/axi_10g_ethernet_nonshared/bd_0/ip/ip_0/bd_7ad4_xmac_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_7ad4_xmac_0 || ORIG_REF_NAME==bd_7ad4_xmac_0} -quiet] -quiet

# IP: ip/axi_10g_ethernet_nonshared/bd_0/ip/ip_1/bd_7ad4_xpcs_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_7ad4_xpcs_0 || ORIG_REF_NAME==bd_7ad4_xpcs_0} -quiet] -quiet

# IP: ip/axi_10g_ethernet_nonshared/bd_0/ip/ip_2/bd_7ad4_dcm_locked_driver_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_7ad4_dcm_locked_driver_0 || ORIG_REF_NAME==bd_7ad4_dcm_locked_driver_0} -quiet] -quiet

# IP: ip/axi_10g_ethernet_nonshared/bd_0/ip/ip_3/bd_7ad4_pma_pmd_type_driver_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_7ad4_pma_pmd_type_driver_0 || ORIG_REF_NAME==bd_7ad4_pma_pmd_type_driver_0} -quiet] -quiet

# IP: ip/fifo_generator_status/fifo_generator_status.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fifo_generator_status || ORIG_REF_NAME==fifo_generator_status} -quiet] -quiet

# IP: ip/inverter_0/inverter_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==inverter_0 || ORIG_REF_NAME==inverter_0} -quiet] -quiet

# IP: ip/fifo_generator_1_9/fifo_generator_1_9.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fifo_generator_1_9 || ORIG_REF_NAME==fifo_generator_1_9} -quiet] -quiet

# IP: ip/nf_10g_interface_ip/nf_10g_interface_ip.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==nf_10g_interface_ip || ORIG_REF_NAME==nf_10g_interface_ip} -quiet] -quiet

# IP: ip/axi_10g_ethernet_shared/axi_10g_ethernet_shared.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi_10g_ethernet_shared || ORIG_REF_NAME==axi_10g_ethernet_shared} -quiet] -quiet

# Block Designs: ip/axi_10g_ethernet_shared/bd_0/bd_a1aa.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_a1aa || ORIG_REF_NAME==bd_a1aa} -quiet] -quiet

# IP: ip/axi_10g_ethernet_shared/bd_0/ip/ip_0/bd_a1aa_xmac_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_a1aa_xmac_0 || ORIG_REF_NAME==bd_a1aa_xmac_0} -quiet] -quiet

# IP: ip/axi_10g_ethernet_shared/bd_0/ip/ip_1/bd_a1aa_xpcs_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_a1aa_xpcs_0 || ORIG_REF_NAME==bd_a1aa_xpcs_0} -quiet] -quiet

# IP: ip/axi_10g_ethernet_shared/bd_0/ip/ip_2/bd_a1aa_dcm_locked_driver_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_a1aa_dcm_locked_driver_0 || ORIG_REF_NAME==bd_a1aa_dcm_locked_driver_0} -quiet] -quiet

# IP: ip/axi_10g_ethernet_shared/bd_0/ip/ip_3/bd_a1aa_pma_pmd_type_driver_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_a1aa_pma_pmd_type_driver_0 || ORIG_REF_NAME==bd_a1aa_pma_pmd_type_driver_0} -quiet] -quiet

# IP: ip/nf_10g_interface_shared_ip/nf_10g_interface_shared_ip.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==nf_10g_interface_shared_ip || ORIG_REF_NAME==nf_10g_interface_shared_ip} -quiet] -quiet

# IP: ip/clk_wiz_ip/clk_wiz_ip.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==clk_wiz_ip || ORIG_REF_NAME==clk_wiz_ip} -quiet] -quiet

# IP: ip/proc_sys_reset_ip/proc_sys_reset_ip.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==proc_sys_reset_ip || ORIG_REF_NAME==proc_sys_reset_ip} -quiet] -quiet

# IP: ip/identifier_ip/identifier_ip.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==identifier_ip || ORIG_REF_NAME==identifier_ip} -quiet] -quiet

# XDC: bd/control_sub/control_sub_ooc.xdc

# XDC: ip/axi_10g_ethernet_nonshared/bd_0/ip/ip_0/synth/bd_7ad4_xmac_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_7ad4_xmac_0 || ORIG_REF_NAME==bd_7ad4_xmac_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: ip/axi_10g_ethernet_nonshared/bd_0/ip/ip_0/synth/bd_7ad4_xmac_0_ooc.xdc

# XDC: ip/axi_10g_ethernet_nonshared/bd_0/ip/ip_1/synth/bd_7ad4_xpcs_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_7ad4_xpcs_0 || ORIG_REF_NAME==bd_7ad4_xpcs_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: ip/axi_10g_ethernet_nonshared/bd_0/ip/ip_1/synth/bd_7ad4_xpcs_0_ooc.xdc

# XDC: ip/axi_10g_ethernet_nonshared/bd_0/ip/ip_1/synth/bd_7ad4_xpcs_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_7ad4_xpcs_0 || ORIG_REF_NAME==bd_7ad4_xpcs_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: ip/axi_10g_ethernet_nonshared/bd_0/bd_7ad4_ooc.xdc

# XDC: ip/axi_10g_ethernet_nonshared/synth/axi_10g_ethernet_nonshared_ooc.xdc

# XDC: ip/fifo_generator_status/fifo_generator_status.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_generator_status || ORIG_REF_NAME==fifo_generator_status} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: ip/fifo_generator_status/fifo_generator_status_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_generator_status || ORIG_REF_NAME==fifo_generator_status} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: ip/fifo_generator_1_9/fifo_generator_1_9.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_generator_1_9 || ORIG_REF_NAME==fifo_generator_1_9} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: ip/fifo_generator_1_9/fifo_generator_1_9_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_generator_1_9 || ORIG_REF_NAME==fifo_generator_1_9} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: ip/axi_10g_ethernet_shared/bd_0/ip/ip_0/synth/bd_a1aa_xmac_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_a1aa_xmac_0 || ORIG_REF_NAME==bd_a1aa_xmac_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: ip/axi_10g_ethernet_shared/bd_0/ip/ip_0/synth/bd_a1aa_xmac_0_ooc.xdc

# XDC: ip/axi_10g_ethernet_shared/bd_0/ip/ip_1/synth/bd_a1aa_xpcs_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_a1aa_xpcs_0 || ORIG_REF_NAME==bd_a1aa_xpcs_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: ip/axi_10g_ethernet_shared/bd_0/ip/ip_1/synth/bd_a1aa_xpcs_0_ooc.xdc

# XDC: ip/axi_10g_ethernet_shared/bd_0/ip/ip_1/synth/bd_a1aa_xpcs_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_a1aa_xpcs_0 || ORIG_REF_NAME==bd_a1aa_xpcs_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: ip/axi_10g_ethernet_shared/bd_0/bd_a1aa_ooc.xdc

# XDC: ip/axi_10g_ethernet_shared/synth/axi_10g_ethernet_shared_ooc.xdc

# XDC: ip/clk_wiz_ip/clk_wiz_ip_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==clk_wiz_ip || ORIG_REF_NAME==clk_wiz_ip} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: ip/clk_wiz_ip/clk_wiz_ip.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==clk_wiz_ip || ORIG_REF_NAME==clk_wiz_ip} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: ip/clk_wiz_ip/clk_wiz_ip_late.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==clk_wiz_ip || ORIG_REF_NAME==clk_wiz_ip} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: ip/clk_wiz_ip/clk_wiz_ip_ooc.xdc

# XDC: ip/proc_sys_reset_ip/proc_sys_reset_ip_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==proc_sys_reset_ip || ORIG_REF_NAME==proc_sys_reset_ip} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: ip/proc_sys_reset_ip/proc_sys_reset_ip.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==proc_sys_reset_ip || ORIG_REF_NAME==proc_sys_reset_ip} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: ip/identifier_ip/identifier_ip_ooc.xdc
