T ?= test01
S ?= 1
TEST_NAME = ${T}
STOP_FAIL = ${S}
run_test:
	# echo ${TEST_NAME}
	# echo ${STOP_FAIL}
	./run_test.sh ${TEST_NAME} ${STOP_FAIL}

run_test_gui:
	./run_test_gui.sh ${TEST_NAME} ${STOP_FAIL}

